// tailwind.config.js
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#001b3c",
        "secondary-container": "#bfd5ff",
        "surface-container-highest": "#e3e2df",
        "outline-variant": "#c1c6d4",
        "secondary": "#495f83",
        "primary": "#004e99",
        "primary-fixed-dim": "#a8c8ff",
        "inverse-on-surface": "#f2f1ee",
        "surface-container-low": "#f4f3f0",
        "surface-container": "#efeeeb",
        "surface": "#faf9f6",
        "tertiary-fixed": "#ffdbca",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed-variant": "#31476a",
        "tertiary-container": "#a94b00",
        "background": "#faf9f6",
        "secondary-fixed-dim": "#b1c7f1",
        "on-tertiary-fixed-variant": "#773300",
        "on-tertiary-container": "#ffe0d1",
        "tertiary": "#833900",
        "error": "#ba1a1a",
        "surface-container-high": "#e9e8e5",
        "on-primary-fixed-variant": "#00468a",
        "on-tertiary": "#ffffff",
        "inverse-surface": "#2f312f",
        "outline": "#727783",
        "on-tertiary-fixed": "#331200",
        "on-primary-fixed": "#001b3d",
        "surface-tint": "#005eb5",
        "surface-bright": "#faf9f6",
        "surface-variant": "#e3e2df",
        "primary-fixed": "#d6e3ff",
        "on-primary-container": "#dbe6ff",
        "tertiary-fixed-dim": "#ffb68e",
        "on-secondary-container": "#465c80",
        "on-error": "#ffffff",
        "on-surface": "#1b1c1a",
        "on-secondary": "#ffffff",
        "on-background": "#1b1c1a",
        "on-error-container": "#93000a",
        "secondary-fixed": "#d6e3ff",
        "on-primary": "#ffffff",
        "primary-container": "#0a66c2",
        "on-surface-variant": "#414752",
        "error-container": "#ffdad6",
        "inverse-primary": "#a8c8ff",
        "surface-dim": "#dbdad7",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};