import '@testing-library/jest-dom'
import { vi } from 'vitest'

// Mock global pour ../services/api
vi.mock('../services/api', () => ({
  authService: {
    login: vi.fn(),
    register: vi.fn(),
    forgotPassword: vi.fn(),
    resetPassword: vi.fn(),
    getComptesEnAttente: vi.fn(),
    getAllUsers: vi.fn(),
    activerCompte: vi.fn(),
    desactiverCompte: vi.fn(),
    changerRole: vi.fn(),
  },
  diplomeService: {
    soumettreDiplome: vi.fn(),
    resoumettreDiplome: vi.fn(),
    getMesDiplomes: vi.fn(),
    archiverDiplome: vi.fn(),
    reactiverDiplome: vi.fn(),
    getDocumentsEnAttente: vi.fn(),
    approuverDiplome: vi.fn(),
    rejeterDiplome: vi.fn(),
    getStatistiques: vi.fn(),
  },
  signalementService: {
    getAll: vi.fn(),
    getDetails: vi.fn(),
    traiter: vi.fn(),
  },
  publicationAdminService: {
    supprimer: vi.fn(),
    getPublicationsEnAttente: vi.fn(),
    validerPublication: vi.fn(),
    refuserPublication: vi.fn(),
  },
  publicationService: {
    supprimer: vi.fn(),
    getPublicationsEnAttente: vi.fn(),
    validerPublication: vi.fn(),
    refuserPublication: vi.fn(),
  },
  adminService: {
    getPublicationsEnAttente: vi.fn(),
    validerPublication: vi.fn(),
    refuserPublication: vi.fn(),
    supprimerPublication: vi.fn(),
    getStatistiques: vi.fn(),
    getNotifications: vi.fn(),
    marquerNotificationLue: vi.fn(),
    activerCompte: vi.fn(),
    desactiverCompte: vi.fn(),
    changerRole: vi.fn(),
    getComptesEnAttente: vi.fn(),
    getAllUsers: vi.fn(),
  },
  statsService: {
    getGlobal: vi.fn(),
  },
  notificationService: {
    getAll: vi.fn(),
    marquerCommeLue: vi.fn(),
  },
  userNotificationService: {
    getAll: vi.fn(),
    marquerCommeLue: vi.fn(),
    marquerToutCommeLu: vi.fn(),
  },
  publicationEnseignantService: {
    getMesPublications: vi.fn(),
    creerPublication: vi.fn(),
    modifierPublication: vi.fn(),
    supprimerPublication: vi.fn(),
    getPublicationDetails: vi.fn(),
  },
  connexionService: {
    envoyerDemande: vi.fn(),
    accepterDemande: vi.fn(),
    refuserDemande: vi.fn(),
    supprimerConnexion: vi.fn(),
    getDemandesRecues: vi.fn(),
    getDemandesEnvoyees: vi.fn(),
    getConnexionsAcceptees: vi.fn(),
    countConnexions: vi.fn(),
    rechercherUtilisateurs: vi.fn(),
    getSuggestions: vi.fn(),
  },
  enseignantEtudiantService: {
    getProfilEtudiant: vi.fn(),
    recommanderEtudiant: vi.fn(),
  },
  messageService: {
    envoyerMessage: vi.fn(),
    getConversations: vi.fn(),
    getMessages: vi.fn(),
    getMessagesByUserId: vi.fn(),
    marquerCommeLu: vi.fn(),
    getNonLusCount: vi.fn(),
    supprimerConversation: vi.fn(),
  },
  socialService: {
    getPublications: vi.fn(),
    reactToPublication: vi.fn(),
    getCommentaires: vi.fn(),
    addCommentaire: vi.fn(),
    signalerPublication: vi.fn(),
  },
  profilService: {
    getMonProfil: vi.fn(),
    updateProfil: vi.fn(),
    updatePassword: vi.fn(),
    getExperiences: vi.fn(),
    addExperience: vi.fn(),
    updateExperience: vi.fn(),
    deleteExperience: vi.fn(),
    getFormations: vi.fn(),
    addFormation: vi.fn(),
    updateFormation: vi.fn(),
    deleteFormation: vi.fn(),
    getCompetences: vi.fn(),
    addCompetence: vi.fn(),
    updateCompetence: vi.fn(),
    deleteCompetence: vi.fn(),
  },
  etudiantProfilService: {
    getMonProfil: vi.fn(),
    updateProfil: vi.fn(),
    getExperiences: vi.fn(),
    addExperience: vi.fn(),
    updateExperience: vi.fn(),
    deleteExperience: vi.fn(),
    getFormations: vi.fn(),
    addFormation: vi.fn(),
    updateFormation: vi.fn(),
    deleteFormation: vi.fn(),
    getCompetences: vi.fn(),
    addCompetence: vi.fn(),
    deleteCompetence: vi.fn(),
    updatePassword: vi.fn(),
  },
  etudiantEnseignantService: {
    getProfilEnseignant: vi.fn(),
    getProfilEtudiant: vi.fn(),
  },
  etudiantPublicationService: {
    getMesPublications: vi.fn(),
    creerPublication: vi.fn(),
    modifierPublication: vi.fn(),
    supprimerPublication: vi.fn(),
  },
  offreEnseignantService: {
    getMesOffres: vi.fn(),
    creerOffre: vi.fn(),
    modifierOffre: vi.fn(),
    supprimerOffre: vi.fn(),
    archiverOffre: vi.fn(),
    reactiverOffre: vi.fn(),
  },
  etudiantDiplomeService: {
    soumettreDiplome: vi.fn(),
    getMesDiplomes: vi.fn(),
    resoumettreDiplome: vi.fn(),
    supprimerDiplome: vi.fn(),
  },
  etudiantOffreService: {
    getAll: vi.fn(),
  },
  default: vi.fn(),
}))
window.HTMLElement.prototype.scrollIntoView = vi.fn(); 
